name: CD

on: 
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  main:
    name: CD
    uses: zysharp/workflows/.github/workflows/cd.yaml@master
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
